var json_home_ui_1={
	retCode:101,
	msg:'请求成功',
	data:{
		res_type:'1001',
		ui:{
			view_id:'0',
			parent_id:'-1',
			visible:'1',
			view_type:'9999',
			view_name:'VgContentLayout',
			view_width:'1080',
			view_height:'1920',
			clickable:'0',
			bg_normal_color:'#ffffffff',
			bg_focus_color:'#ffffffff',
			view_of:['-1','-1','-1','-1'],
			view_paddings:['0','0','0','0'],
			view_margins:['0','0','0','0'],
			layout_mode:'1',
			refs:[],
			validation:[],
			res_key:'null',
			childs:[
				{
					view_id:'1',
					parent_id:'0',
					visible:'1',
					view_type:'20006',
					view_name:'ActionBar',
					view_width:'1080',
					view_height:'136',
					bg_normal_color:'#ffD01109',
					bg_focus_color:'#ffD01109',
					view_of:['-1','-1','-1','-1'],
					view_paddings:['0','0','0','0'],
					view_margins:['0','0','0','0'],
					layout_mode:'1',
					refs:[],
					validation:[],
					res_key:'',
					childs:[
						{
							view_id:'2',
							parent_id:'1',
							visible:'1',
							view_type:'10003',
							view_name:'VgTextView',
							view_width:'256',
							view_height:'144',
							bg_normal_color:'',
							bg_focus_color:'',
							view_of:['-1','-1','-1','-1'],
							view_paddings:['10','10','10','10'],
							view_margins:['412','0','412','0'],
							refs:[],
							validation:[],
							res_key:'null',
							text:'常用资料',
							input_type:'1',
							hint:'',
							text_size:'48',
							text_align:"0",
							text_color:'#ffffffff',
							childs:[]
						},{
							view_id:'18',
							parent_id:'1',
							visible:'1',
							view_type:'10005',
							view_name:'VgImageView',
							view_width:'144',
							view_height:'144',
							bg_normal_color:'#00000000',
							bg_focus_color:'#00000000',
							view_of:['-1','-1','-1','-1'],
							view_paddings:['15','20','15','20'],
							view_margins:['936','0','0','0'],
							ref_views:[],
							validation:[],
							scaleType:'2',
							imageUrl:'http://192.168.16.198:8080/self_icon_default.png',
							res_key:'',
							childs:[]
						}
					]
				},
				{
					view_id:'30',
					parent_id:'0',
					visible:'1',
					view_type:'10010',
					isShowBar:'0',
					view_name:'VgContentLayout',
					view_width:'1080',
					view_height:'1920',
					clickable:'0',
					bg_normal_color:'#ffffffff',
					bg_focus_color:'#ffffffff',
					view_of:['-1','1','-1','-1'],
					view_paddings:['0','0','0','0'],
					view_margins:['0','0','0','0'],
					layout_mode:'1',
					ref_views:[],
					validation:[],
					res_key:'null',
					childs:[
					{
						view_id:'3',
						parent_id:'0',
						visible:'1',
						view_type:'20010',
						view_name:'VgGalleryView',
						view_width:'1080',
						view_height:'480',
						noScroll:'0',
						interval:'5000',
						bg_normal_color:'#ffffffff',
						bg_focus_color:'#ffffffff',
						view_of:['-1','1','-1','-1'],
						view_paddings:['0','0','0','0'],
						view_margins:['0','0','0','0'],
						ref_views:[],
						validation:[],
						res_key:'null',
						childs:[
							{
								view_id:'4',
								parent_id:'3',
								visible:'1',
								view_type:'10005',
								view_name:'VgImageView',
								view_width:'1080',
								view_height:'480',
								bg_normal_color:'#00000000',
								bg_focus_color:'#00000000',
								view_of:['-1','-1','-1','-1'],
								view_paddings:['0','0','0','0'],
								view_margins:['0','0','0','0'],
								ref_views:[],
								validation:[],
								scaleType:'1',
								imageUrl:'http://img2.51tietu.net/upload/www.51tietu.net/2016-051200/20160512005305urmh4f3xi2v33175.jpg',
								res_key:'',
								childs:[]
							},
							{
							view_id:'5',
							parent_id:'3',
							visible:'1',
							view_type:'10005',
							view_name:'VgImageView',
							view_width:'1080',
							view_height:'480',
							bg_normal_color:'#00000000',
							bg_focus_color:'#00000000',
							view_of:['-1','-1','-1','-1'],
							view_paddings:['0','0','0','0'],
							view_margins:['0','0','0','0'],
							ref_views:[],
							validation:[],
							scaleType:'1',
							imageUrl:'http://img2.51tietu.net/upload/www.51tietu.net/2016-051200/20160512005303hqidz5jr4hu33167.jpg',
							res_key:'',
							childs:[]
						},
						{
							view_id:'6',
							parent_id:'3',
							visible:'1',
							view_type:'10005',
							view_name:'VgImageView',
							view_width:'1080',
							view_height:'480',
							bg_normal_color:'#00000000',
							bg_focus_color:'#00000000',
							view_of:['-1','-1','-1','-1'],
							view_paddings:['0','0','0','0'],
							view_margins:['0','0','0','0'],
							ref_views:[],
							validation:[],
							scaleType:'1',
							imageUrl:'http://img2.51tietu.net/upload/www.51tietu.net/2016-051200/20160512005305eqzpeoz51gs33174.jpg',
							res_key:'',
							childs:[]
						}
						]
					},
					{
						view_id:'6',
						parent_id:'0',
						visible:'1',
						view_type:'9999',
						view_name:'VgContentLayout',
						view_width:'1080',
						clickable:'0',
						view_height:'300',
						bg_normal_color:'#ffffffff',
						bg_focus_color:'#ffffffff',
						view_of:['-1','3','-1','-1'],
						view_paddings:['0','0','0','0'],
						view_margins:['0','0','0','0'],
						ref_views:[],
						validation:[],
						res_key:'null',
						childs:[
						{
							view_id:'7',
							parent_id:'6',
							visible:'1',
							view_type:'10001',
							view_name:'VgTextView',
							view_width:'255',
							view_height:'255',
							bg_normal_color:'#ff00ff00',
							bg_focus_color:'#ff00ff00',
							view_of:['-1','-1','-1','-1'],
							view_paddings:['0','0','0','0'],
							view_margins:['12','12','0','12'],
							ref_views:[],
							validation:[],
							res_key:'null',
							text:'故障分析',
							input_type:'1',
							hint:'',
							text_size:'56',
							text_align:"0",
							text_color:'#ff00ff00',
							childs:[]
						},
						{
							view_id:'8',
							parent_id:'6',
							visible:'1',
							view_type:'10001',
							view_name:'VgTextField',
							view_width:'255',
							view_height:'255',
							bg_normal_color:'#ffffff00',
							bg_focus_color:'#ff00ff00',
							view_of:['7','-1','-1','-1'],
							view_paddings:['0','0','0','0'],
							view_margins:['12','12','0','12'],
							ref_views:[],
							validation:[],
							res_key:'username',
							text:'故障码',
							password:'0',
							text_align:"0",
							input_type:'1',
							hint:'',
							text_size:'56',
							text_color:'#ff000000',
							childs:[]
						},
						{
							view_id:'9',
							parent_id:'6',
							visible:'1',
							view_type:'10001',
							view_name:'VgTextField',
							view_width:'255',
							view_height:'255',
							bg_normal_color:'#ffff00ff',
							bg_focus_color:'#ff00ff00',
							view_of:['8','-1','-1','-1'],
							view_paddings:['0','0','0','0'],
							view_margins:['12','12','0','12'],
							ref_views:[],
							validation:[],
							res_key:'username',
							text:'常用资料',
							password:'0',
							text_align:"0",
							input_type:'1',
							hint:'',
							text_size:'56',
							text_color:'#ff000000',
							childs:[]
						},
						{
							view_id:'10',
							parent_id:'6',
							visible:'1',
							view_type:'10001',
							view_name:'VgTextField',
							view_width:'255',
							view_height:'255',
							bg_normal_color:'#ff00ff00',
							bg_focus_color:'#ff00ff00',
							view_of:['9','-1','-1','-1'],
							view_paddings:['0','0','0','0'],
							view_margins:['12','12','12','12'],
							ref_views:[],
							validation:[],
							res_key:'username',
							text:'维修店',
							password:'0',
							text_align:"0",
							input_type:'1',
							hint:'',
							text_size:'56',
							text_color:'#ff000000',
							childs:[]
						}]
					},
					{
						view_id:'11',
						parent_id:'0',
						visible:'1',
						view_type:'9999',
						view_name:'VgContentLayout',
						view_width:'1080',
						view_height:'280',
						clickable:'0',
						bg_normal_color:'#ffffffff',
						bg_focus_color:'#ffffffff',
						view_of:['-1','6','-1','-1'],
						view_paddings:['0','0','0','0'],
						view_margins:['0','10','0','10'],
						ref_views:[],
						validation:[],
						res_key:'null',
						childs:[
							{
								view_id:'12',
								parent_id:'11',
								visible:'1',
								view_type:'10001',
								view_name:'VgTextView',
								view_width:'255',
								view_height:'255',
								bg_normal_color:'#ff00ff00',
								bg_focus_color:'#ff00ff00',
								view_of:['-1','-1','-1','-1'],
								view_paddings:['0','0','0','0'],
								view_margins:['12','0','0','12'],
								ref_views:[],
								validation:[],
								res_key:'null',
								text:'汽修案例',
								input_type:'1',
								hint:'',
								text_size:'56',
								text_align:"0",
								text_color:'#ff0000ff',
								childs:[]
							},
							{
								view_id:'13',
								parent_id:'11',
								visible:'1',
								view_type:'10001',
								view_name:'VgTextField',
								view_width:'255',
								view_height:'255',
								bg_normal_color:'#ff00ff00',
								bg_focus_color:'#ff00ff00',
								view_of:['12','-1','-1','-1'],
								view_paddings:['0','0','0','0'],
								view_margins:['12','0','0','12'],
								ref_views:[],
								validation:[],
								res_key:'userpass',
								text:'技师学堂',
								input_type:'2',
								password:'1',
								text_align:'0',
								hint:'请填写密码',
								text_size:'56',
								text_color:'#ff000000',
								childs:[]
							},
							{
								view_id:'14',
								parent_id:'11',
								visible:'1',
								view_type:'10001',
								view_name:'VgTextField',
								view_width:'255',
								view_height:'255',
								bg_normal_color:'#ff00ff00',
								bg_focus_color:'#ff00ff00',
								view_of:['13','-1','-1','-1'],
								view_paddings:['0','0','0','0'],
								view_margins:['12','0','0','12'],
								ref_views:[],
								validation:[],
								res_key:'userpass',
								text:'提需求',
								input_type:'2',
								password:'1',
								text_align:'0',
								hint:'请填写密码',
								text_size:'56',
								text_color:'#ff000000',
								childs:[]
							},
							{
								view_id:'15',
								parent_id:'11',
								visible:'1',
								view_type:'10001',
								view_name:'VgTextField',
								view_width:'255',
								view_height:'255',
								bg_normal_color:'#ff00ff00',
								bg_focus_color:'#ffffcccc',
								view_of:['14','-1','-1','-1'],
								view_paddings:['0','0','0','0'],
								view_margins:['12','0','12','12'],
								ref_views:[],
								validation:[],
								res_key:'userpass',
								text:'积分换购',
								input_type:'2',
								password:'1',
								text_align:'0',
								hint:'请填写密码',
								text_size:'56',
								text_color:'#ff000000',
								childs:[]
							}
						]
				},
					{
						view_id:'19',
						parent_id:'0',
						visible:'1',
						view_type:'10009',
						view_name:'VgTextField',
						view_width:'1080',
						view_height:'1800',
						bg_normal_color:'#ff00ff00',
						bg_focus_color:'#ffffcccc',
						view_of:['-1','11','-1','-1'],
						view_paddings:['30','0','0','0'],
						view_margins:['12','0','12','12'],
						ref_views:[],
						validation:[],
						res_key:'userpass',
						text:'技师学堂',
						input_type:'2',
						password:'1',
						text_align:'1',
						hint:'',
						text_size:'56',
						text_color:'#ff000000',
						childs:[]
					}]








				}
			]
		},
		eventLink:[
			{
				event_type:'1002',
				view_id:'17',
				actionLink:[{
					actionType:'10007',
					show_type:'0',
					url:'http://192.168.16.198:8083/',
					ref_ui:[],
					params:[
						'device_id=12345678',
						'code=panelUI'
					],
					modify:[]
				}]
			},
			{
				event_type:'1002',
				view_id:'4',
				actionLink:[{
					actionType:'10007',
					show_type:'0',
					url:'http://192.168.16.198:8083/',
					ref_ui:[],
					params:[
						'device_id=12345678',
						'code=panelUI'
					],
					modify:[]
				}]
			},
			{
				event_type:'1002',
				view_id:'5',
				actionLink:[{
					actionType:'10007',
					show_type:'0',
					url:'http://192.168.16.198:8083/',
					ref_ui:[],
					params:[
						'device_id=12345678',
						'code=panelUI'
					],
					modify:[]
				}]
			},
			{
				event_type:'1002',
				view_id:'17',
				actionLink:[{
					actionType:'10007',
					show_type:'0',
					url:'http://192.168.16.198:8083/',
					ref_ui:[],
					params:[
						'device_id=12345678',
						'code=userCenter'
					],
					modify:[]
				}]
			},
			{
				event_type:'1002',
				view_id:'18',
				actionLink:[{
					actionType:'10007',
					show_type:'0',
					url:'http://192.168.16.198:8083/',
					ref_ui:[],
					params:[
						'device_id=12345678',
						'code=userCenter'
					],
					modify:[]
				}]
			},
			{
				event_type:'1002',
				view_id:'7',
				actionLink:[{
					actionType:'10007',
					show_type:'0',
					url:'http://192.168.16.198:8083/',
					ref_ui:[],
					params:[
						'device_id=12345678',
						'code=userCenter'
					],
					modify:[]
				}]
			},
			{
				event_type:'1002',
				view_id:'8',
				actionLink:[{
					actionType:'10007',
					show_type:'0',
					url:'http://192.168.16.198:8083/',
					ref_ui:[],
					params:[
						'device_id=12345678',
						'code=userCenter'
					],
					modify:[]
				}]
			},
			{
				event_type:'1002',
				view_id:'9',
				actionLink:[{
					actionType:'10007',
					show_type:'0',
					url:'http://192.168.16.198:8083/',
					ref_ui:[],
					params:[
						'device_id=12345678',
						'code=userCenter'
					],
					modify:[]
				}]
			},
			{
				event_type:'1002',
				view_id:'10',
				actionLink:[{
					actionType:'10007',
					show_type:'0',
					url:'http://192.168.16.198:8083/',
					ref_ui:[],
					params:[
						'device_id=12345678',
						'code=userCenter'
					],
					modify:[]
				}]
			},
			{
				event_type:'1002',
				view_id:'12',
				actionLink:[{
					actionType:'10007',
					show_type:'0',
					url:'http://192.168.16.198:8083/',
					ref_ui:[],
					params:[
						'device_id=12345678',
						'code=userCenter'
					],
					modify:[]
				}]
			},
			{
				event_type:'1002',
				view_id:'13',
				actionLink:[{
					actionType:'10007',
					show_type:'0',
					url:'http://192.168.16.198:8083/',
					ref_ui:[],
					params:[
						'device_id=12345678',
						'code=userCenter'
					],
					modify:[]
				}]
			},
			{
				event_type:'1002',
				view_id:'14',
				actionLink:[{
					actionType:'10007',
					show_type:'0',
					url:'http://192.168.16.198:8083/',
					ref_ui:[],
					params:[
						'device_id=12345678',
						'code=userCenter'
					],
					modify:[]
				}]
			},
			{
				event_type:'1002',
				view_id:'15',
				actionLink:[{
					actionType:'10007',
					show_type:'0',
					url:'http://192.168.16.198:8083/',
					ref_ui:[],
					params:[
						'device_id=12345678',
						'code=userCenter'
					],
					modify:[]
				}]
			}
		]
	}
};
function loadHome1(req,res,DATA){
	var string =JSON.stringify(json_home_ui_1);
	res.end(string);
}
exports.loadHome1=loadHome1;