var json_panel_ui={
		retCode:101,
		msg:'请求成功',
		data:{
			res_type:'1001',
			ui:{
				view_id:'0',
				parent_id:'-1',
				view_type:'9999',
				visible:'1',
				view_name:'VgContentLayout',
				view_width:'1080',
				view_height:'1920',
				clickable:'0',
				bg_normal_color:'#ffffffff',
				bg_focus_color:'#ffffffff',
				view_of:['-1','-1','-1','-1'],
				view_paddings:['0','0','0','0'],
				view_margins:['0','0','0','0'],
				ref_views:[],
				validation:[],
				res_key:'null',
				childs:[{
					view_id:'1',
					parent_id:'-1',
					visible:'1',
					view_type:'20006',
					view_name:'VgTopActionBar',
					view_width:'1080',
					view_height:'156',
					bg_normal_color:'#ffD01109',
					bg_focus_color:'#ffD01109',
					view_of:['-1','-1','-1','-1'],
					view_paddings:['0','0','0','0'],
					view_margins:['0','0','0','0'],
					ref_views:[],
					validation:[],
					res_key:'null',
					childs:[{
							view_id:'2',
							parent_id:'1',
							visible:'1',
							view_type:'10003',
							view_name:'VgTextView',
							view_width:'156',
							view_height:'156',
							bg_normal_color:'#00000000',
							bg_focus_color:'#00000000',
							view_of:['-1','-1','-1','-1'],
							view_paddings:['36','10','10','10'],
							view_margins:['0','0','0','0'],
							ref_views:[],
							validation:[],
							res_key:'null',
							text:'返回',
							input_type:'1',
							hint:'',
							text_size:'48',
							text_align:"0",
							text_color:'#ffffffff',
							childs:[]
						}]
					},{
						view_id:'3',
						parent_id:'1',
						view_type:'10001',
						view_name:'VgTextView',
						view_width:'256',
						visible:'1',
						view_height:'136',
						bg_normal_color:'#ffff0000',
						bg_focus_color:'#ffff0000',
						view_of:['-1','-1','-1','-1'],
						view_paddings:['10','10','10','10'],
						view_margins:['412','370','412','10'],
						ref_views:[],
						validation:[],
						res_key:'null',
						text:'汽修案例',
						input_type:'1',
						hint:'',
						text_size:'48',
						text_align:"0",
						text_color:'#ff00ff00',
						childs:[]
					}]
		},
		eventLink:[{
			event_type:'1002',
			view_id:'2',
			actionLink:[{
				actionType:'10008',
				show_type:'0',
				url:'http://192.168.16.198:8083/',
				ref_ui:[],
				params:[
					'device_id=12345678',
					'code=panelUI'
				],
				modify:[]
			}]
		}]
	}
};
function panel(req,res,data){
	
	var string =JSON.stringify(json_panel_ui);
	res.end(string);
}
exports.panel=panel;