
{
    view_id:'1',
    parent_id:'0',
    visible:'1',
    view_type:'20008',
    view_name:'VgViewPager',
    view_width:'1080',
    view_height:'1920',
    noScroll:'1',/*是否可以左右滑动*/
    bg_normal_color:'#ffffffff',
    bg_focus_color:'#ffffffff',
    view_of:['-1','-1','-1','2'],
    view_paddings:['0','0','0','0'],
    view_margins:['0','0','0','0'],
    ref_views:[],
    validation:[],
    res_key:'null',
    childs:[]
}